// Plugin Docusaurus : Génère un fichier docsMetadata.json à partir des frontmatters
// des fichiers Markdown d’un dossier de documentation (docs/01-cours par défaut,
// configurable via l’option docsDir).

const fs = require("fs");
const path = require("path");

// Dossier lu par défaut, relatif à la racine du site Docusaurus
const DEFAULT_DOCS_DIR = "docs/01-cours";

/**
 * Extrait le frontmatter d'un contenu Markdown
 * @param {string} content
 * @returns {Object} frontmatter
 */
function extractFrontmatter(content) {
  const match = content.match(/^---([\s\S]*?)---/);
  if (!match) return null;
  const frontmatter = {};
  match[1].split("\n").forEach((line) => {
    const [key, ...rest] = line.split(":");
    if (key && rest.length) {
      let value = rest.join(":").trim();
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1);
      }
      frontmatter[key.trim()] = value;
    }
  });
  return frontmatter;
}

/**
 * Extrait le premier en-tete Markdown de niveau 1 (# Titre) hors frontmatter.
 * @param {string} content
 * @returns {string|undefined}
 */
function extractFirstMarkdownTitle(content) {
  const withoutFrontmatter = content.replace(/^---[\s\S]*?---\s*/, "");
  const match = withoutFrontmatter.match(/^#\s+(.+)$/m);
  return match ? match[1].trim() : undefined;
}

/**
 * Déduit le segment de route à partir du dossier des docs, en retirant le dossier
 * racine des docs et les préfixes numériques (ex : docs/01-notes -> notes)
 * @param {string} siteDir - Racine du site Docusaurus
 * @param {string} docsDir - Chemin absolu du dossier des fichiers Markdown
 * @returns {string}
 */
function deriveRouteBasePath(siteDir, docsDir) {
  return path
    .relative(siteDir, docsDir)
    .split(path.sep)
    .slice(1) // retire le dossier racine des docs (docs/)
    .map((segment) => segment.replace(/^[0-9]+-/, ""))
    .filter(Boolean)
    .join("/");
}

/**
 * Retourne le chemin absolu du fichier docsMetadata.json dans static/
 * @returns {string}
 */
function getStaticMetadataPath() {
  return path.resolve(__dirname, "../../static/docsMetadata.json");
}

/**
 * Extrait les métadonnées (frontmatter) de tous les fichiers .md d'un dossier
 * @param {Object} params
 * @param {string} params.docsDir - Chemin du dossier contenant les fichiers Markdown
 * @returns {Array<Object>} Tableau d'objets métadonnées
 */
function getAllDocsMetadata({ docsDir }) {
  const docs = [];
  const files = fs.readdirSync(docsDir);
  for (const file of files) {
    if (!/\.mdx?$/.test(file)) continue;
    const docPath = path.join(docsDir, file);
    const content = fs.readFileSync(docPath, "utf-8");
    const frontmatter = extractFrontmatter(content) || {};
    const markdownTitle = extractFirstMarkdownTitle(content);
    docs.push({
      id: file.replace(/\.mdx?$/, ""),
      ...frontmatter,
      _documentTitle: markdownTitle,
    });
  }
  return docs;
}

/**
 * Extrait tous les objets avec tous les champs présents dans item pour les entrées de type 'doc',
 * et {id} pour 'autogenerated'.
 * @param {Array} items
 * @returns {Array<Object>}
 */
function extractAllDocEntries(items) {
  let entries = [];
  for (const item of items) {
    if (item.type === "doc" && item.id) {
      // Inclure tous les champs de l'item (shallow copy)
      entries.push({ ...item });
    } else if (item.type === "category" && Array.isArray(item.items)) {
      entries = entries.concat(extractAllDocEntries(item.items));
    } else if (item.type === "autogenerated" && item.dirName) {
      const dirPath = path.resolve(__dirname, `../../docs/${item.dirName}`);
      if (fs.existsSync(dirPath)) {
        const files = fs.readdirSync(dirPath);
        files.forEach((file) => {
          if (/\.mdx?$/.test(file)) {
            entries.push({ id: file.replace(/\.mdx?$/, "") });
          }
        });
      }
    }
  }
  return entries;
}

/**
 * Génère le fichier sidebarDocs.js à partir de sidebars.js
 */
function generateSidebarDocs() {
  const sidebarPath = path.resolve(__dirname, "../../sidebars.js");
  const outputPath = path.resolve(
    __dirname,
    "../../src/components/MainDocsGrid/sidebarDocs.js"
  );
  const sidebars = require(sidebarPath);
  // Ne prendre que la section 'docs'
  let allEntries = [];
  if (Array.isArray(sidebars.docs)) {
    allEntries = extractAllDocEntries(sidebars.docs);
  }
  const content =
    "// Ce fichier est généré automatiquement à partir de sidebars.js\n" +
    "export default " +
    JSON.stringify(allEntries, null, 2) +
    ";\n";
  fs.writeFileSync(outputPath, content);
}

/**
 * Plugin Docusaurus pour exposer les métadonnées des documents
 * @param {Object} context - Contexte Docusaurus
 * @param {Object} [options]
 * @param {string} [options.docsDir] - Dossier des fichiers Markdown à lire,
 *   relatif à la racine du site (ou chemin absolu). Défaut : docs/01-cours
 * @param {string} [options.routeBasePath] - Segment de route sous lequel ces docs
 *   sont publiés, exposé aux composants. Défaut : déduit de docsDir
 */
module.exports = function pluginDocsMetadata(context, options) {
  const siteDir = context?.siteDir || path.resolve(__dirname, "../..");
  const docsDir = path.resolve(siteDir, options?.docsDir || DEFAULT_DOCS_DIR);
  const routeBasePath =
    options?.routeBasePath ?? deriveRouteBasePath(siteDir, docsDir);

  return {
    name: "docusaurus-plugin-docs-metadata",
    /**
     * Chargement des métadonnées à partir des fichiers Markdown
     */
    async loadContent() {
      return getAllDocsMetadata({ docsDir });
    },
    /**
     * Expose le segment de route aux composants et génère le fichier
     * docsMetadata.json dans static/ pour qu'il soit déployé
     */
    async contentLoaded({ content, actions }) {
      actions.setGlobalData({ routeBasePath });
      fs.writeFileSync(
        getStaticMetadataPath(),
        JSON.stringify(content, null, 2)
      );
      generateSidebarDocs(); // Génère sidebarDocs.js à chaque build
    },
  };
};
