// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  cours:      [{type: 'autogenerated', dirName: 'rencontres'}],
  notions:    [{type: 'autogenerated', dirName: 'notions'}],
  tp:         [{type: 'autogenerated', dirName: 'tp'}],
  exercices:  [{type: 'autogenerated', dirName: 'exercices'}],
};

module.exports = sidebars;
