name: Tester le build

on:
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Tester le build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache-dependency-path: "**/package-lock.json"
          node-version: 24
          cache: npm
      - name: Installer les dépendances
        working-directory: ./web
        run: npm ci
      - name: Build du site
        working-directory: ./web
        run: npm run build
