// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: "doc",
      label: "1.1 - Intro 🏁",
      id: "cours/rencontre1.1",
    },
    {
      type: "doc",
      label: "1.2 - Mise en page 📄",
      id: "cours/rencontre1.1",
    },
  ],
  tp: [{ type: "autogenerated", dirName: "02-tp" }],
};

module.exports = sidebars;
