// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: "doc",
      label: "R01 - Introduction au cours",
      id: "cours/rencontre1.1",
    },
    {
      type: "doc",
      label: "R02 - Variables, chaînes, opérations, debugger",
      id: "cours/rencontre1.2",
    },
    {
      type: "doc",
      label: "R03 - Structures conditionnelles, booléens, pseudo-code",
      id: "cours/rencontre2.1",
    },
    {
      type: "doc",
      label: "R04 - Méthodes, valeurs de retour, portée",
      id: "cours/rencontre2.2",
    },
    {
      type: "doc",
      label: "R05 - Intégration des méthodes",
      id: "cours/rencontre3.1",
    },
    {
      type: "doc",
      label: "R06 - TP1 Fiche personnelle",
      id: "cours/rencontre3.2",
    },
    {
      type: "doc",
      label: "R07 - Remise TP1, tableaux 1D, TP2, chaînes",
      id: "cours/rencontre4.1",
    },
    {
      type: "doc",
      label: "R08 - Boucles for, tableaux, recherche",
      id: "cours/rencontre4.2",
    },
    {
      type: "doc",
      label: "R09 - Intégration des notions",
      id: "cours/rencontre5.1",
    },
    { type: "doc", label: "R10 - Formative 1", id: "cours/rencontre5.2" },
    { type: "doc", label: "R11 - Examen 1", id: "cours/rencontre6.1" },
    { type: "doc", label: "R12 - Tableaux 2D", id: "cours/rencontre6.2" },
    {
      type: "doc",
      label: "R13 - Parcours de tableaux 2D",
      id: "cours/rencontre7.1",
    },
    {
      type: "doc",
      label: "R14 - Switch, while, do while",
      id: "cours/rencontre7.2",
    },
    {
      type: "doc",
      label: "R15 - Intégration des notions vues",
      id: "cours/rencontre8.1",
    },
    { type: "doc", label: "R16 - TP2 Mini RPG", id: "cours/rencontre8.2" },
    {
      type: "doc",
      label: "R17 - Remise TP2, lecture fichiers",
      id: "cours/rencontre9.1",
    },
    {
      type: "doc",
      label: "R18 - Écriture dans un fichier",
      id: "cours/rencontre9.2",
    },
    {
      type: "doc",
      label: "R19 - Fichiers CSV et séparateurs",
      id: "cours/rencontre10.1",
    },
    { type: "doc", label: "R20 - Formative 2", id: "cours/rencontre10.2" },
    { type: "doc", label: "R21 - Sommatif 2", id: "cours/rencontre11.1" },
    { type: "doc", label: "R22 - TP3 RPG avancé", id: "cours/rencontre11.2" },
    { type: "doc", label: "R23 - TP3 suite", id: "cours/rencontre12.1" },
    {
      type: "doc",
      label: "R24 - Remise TP3, interface graphique",
      id: "cours/rencontre12.2",
    },
    {
      type: "doc",
      label: "R25 - Introduction à la POO",
      id: "cours/rencontre13.1",
    },
    {
      type: "doc",
      label: "R26 - Intégration des objets",
      id: "cours/rencontre13.2",
    },
    { type: "doc", label: "R27 - TP4", id: "cours/rencontre14.1" },
    { type: "doc", label: "R28 - TP4 suite", id: "cours/rencontre14.2" },
    {
      type: "doc",
      label: "R29 - Remise TP4, Formative 3",
      id: "cours/rencontre15.1",
    },
    { type: "doc", label: "R30 - Sommatif 3", id: "cours/rencontre15.2" },
  ],
  tp: [
    { type: "doc", label: "TP1", id: "tp/tp1" },
    { type: "doc", label: "TP2", id: "tp/tp2" },
    { type: "doc", label: "TP3", id: "tp/tp3" },
  ],
  
  laboratoire: [{ type: "autogenerated", dirName: "03-laboratoire" }],
};


module.exports = sidebars;
